### ISSUE TITLE
add an option to use src folder for the package code

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#25]
Probably we can resolve this using post generation hook: https://github.com/osl-incubator/cookiecutter-python/blob/main/hooks/post_gen_project.py

**Comment by YurelyCamacho** [comment]
@xmnlab Can you please give me some advice on how to solve this?

**Comment by xmnlab** [comment]
sure! please check out theses pages:

* https://medium.com/mlearning-ai/a-practical-guide-to-python-project-structure-and-packaging-90c7f7a04f95
* https://py-pkgs.org/04-package-structure.html#package-structure
