### ISSUE TITLE
Add pydocstyle to the template

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#37]
ref: http://www.pydocstyle.org/en/stable/

add pydocstyle as an option to the template, if it is selected it should be added as a dependency (dev) and should be included to the pre-commit hook

**Comment by xmnlab** [comment]
let's use it for a training session

cc @esloch @anavelyz @yurelycamacho @DamarisMartina

**Comment by YurelyCamacho** [comment]
@xmnlab Will this be used as a training session or not? Thanks

**Comment by xmnlab** [comment]
I don't remember why was the training session .. but probably it didn't happen.
feel free to pick this one!
