### ISSUE TITLE
Publish from semantic release to pypi

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#43]
Add to the semantic release pipeline a step for publishing to pypi

ref: https://github.com/thegraphnetwork/epigraphhub_py/blob/main/.releaserc.json#L59

**Comment by xmnlab** [comment]
additionally, it should have some env variables and it needs to run a poetry command in order to set the credentials to pypi:

https://github.com/thegraphnetwork/epigraphhub_py/blob/main/.github/workflows/release.yaml#L27-L31

**Comment by xmnlab** [comment]
additionally, as we will use poetry for  build and publish, we need to install it on CI with a conda environment.
in another words, we need to add this: https://github.com/thegraphnetwork/epigraphhub_py/blob/main/.github/workflows/release.yaml#L16

**Comment by xmnlab** [comment]
for now we don't need to publish to pypi because the template is not a package.
maybe in the future, if we would like to have it as a package we can re-open this issue.

**Comment by xmnlab** [comment]
oops, sorry. this implementation would be done for the template not for the project.

**Comment by DamarisMartina** [comment]
Hi can I work on this issue?
