### ISSUE TITLE
Publish the documentation to github pages in the release workflow

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#46]
Our template should publish the documentation to the github actions in the release workflow

ref: https://github.com/arxlang/arx/blob/main/.github/workflows/release.yaml#L62-L72

**Comment by Anavelyz** [comment]
This issue was resolved in: fix(release): improve semantic release github action workflow (https://github.com/osl-incubator/cookiecutter-python/pull/78)

@xmnlab please check this

**Comment by xmnlab** [comment]
awesome. good catch. thanks!
