### ISSUE TITLE
Research Governance standards

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/cookiecutter-python#51]
Add an option for governance document, called governance_document_based_on,  with the following options:

- [ ] NumPy governance document
- [ ] SciML governance document
- [ ] None

**Comment by xmnlab** [comment]
IIRC numpy governance doc is one of the most popular one.

**Comment by Saransh-cpp** [comment]
[SciML's governance model](https://sciml.ai/governance/) is quite popular too. We use it as it is at [PyBaMM](https://github.com/pybamm-team/PyBaMM/wiki/Governance). An option that we can add for the users.

**Comment by xmnlab** [comment]
very nice, thanks @Saransh-cpp for sharing! I updated the first comment with the options for this
